name = "Veterename"
uid = "EE500612-B7E6-48DF-A24A-B30645A88D5E"
version = 2
copyright = ""
description = "Renames veteran units"
author = "Cobrand"
url = ""
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
