name = "ScalableRename"
uid = "cb3b020d-7bc7-43cc-b142-68eaac2ed3f3"
version = 1
copyright = "MIT open source lisence (https://opensource.org/licenses/MIT)"
description = 'Renames units with decreasing rate during the game in order to avoid spamming names like other mods. It is based on "Veterename" by Cobrand.'
author = "peterpji"
url = "https://github.com/peterpji/faf_unit_naming"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
