local NameTable = {
    Default = { -- land units
        "Destiny",
        "Infinity",
        "Void",
        "Overcharge",
        "Neo",
    },
    UEFT4table = {
        "George Washington",
        "John Adams",
        "Thomas Jefferson",
        "James Madison",
        "James Monroe",
        "John Q. Adams",
        "Andrew Jackson",
        "Martin Van Buren",
        "William H. Harrison",
        "John Tyler",
        "James K. Polk",
        "Zachary Taylor",
        "Millard Fillmore",
        "Franklin Pierce",
        "James Buchanan",
        "Abraham Lincoln",
        "Andrew Johnson",
        "Ulysses S. Grant",
        "Rutherford B. Hayes",
        "James A. Gardield",
        "Chester A. Arthur",
        "S. Grover Cleveland",
        "Benjamin Harrison",
        "William McKinley",
        "Theodore Roosevelt",
        "William H. Taft",
        "T.Woodrow Wilson",
        "Warren G. Harding",
        "J. Calvin Coolidge",
        "Herbet C. Hoover",
        "Franlin D. Roosevelt",
        "Harry S. Truman",
        "Dwight D. Eisenhower",
        "John F. Kennedy",
        "Lyndon B. Johnson",
        "Richard M. Nixon",
        "Gerald R. Ford",
        "James E. Carter",
        "Ronald W. Reagan",
        "George H. W. Bush",
        "William J. 'Bill' Clinton",
        "George W. Bush",
        "Barack Obama",
        "Bernie Sanders",
    },
    AeonT4table = {
        "UFO",
    },
    SeraphimT4table = {
        "Obvious alien is obvious",
    },
    CybranT4table = {
        "Obvious Troll is obvious",
        "This is a mantis",
        "Captain sneak",
    },
    AirTable = {
        "Eagle",
        "Owl",
        "Falcon",
        "Griffin",
    },
    Naval = {
        "Nessie",
        "Jormungandr",
        "The Kraken",
    },
    BNaval = {
        "Leviathan",
        "Carcinos",
    },
    Gunships = {
        "Snake",
        "Starvation",
        "Nidhogg",
        "Phoenix",
    },
    Defense = {
        "I am expansive",
        "Killer",
        "AWW YEAA",
        "THIS IS SPARTA",
        "mega turret",
        "Thousand flames",
        "You are an idiot",
    },
    Structures = {
        "Nuker",
        "Alpha",
        "Foxtrot",
        "Beta",
        "Charlie",
        "Echo",
        "Golf",
        "Juliett",
        "November",
    }
}

function GetTable()
    return NameTable;
end